name: Openwrt Build

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master
env:
  repo_url: https://github.com/openwrt/openwrt.git
  repo_tag: v23.05.4
  TZ: Asia/Shanghai
  home_dir: /mnt/app

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: "释放部分系统空间"
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false

          # all of these default to true, but feel free to set to
          # false if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: false
          swap-storage: false
      - uses: actions/checkout@v4
      - name: "编译系统初始化"
        run: |
          sudo apt-get update
          sudo apt-get install -y time git-core subversion build-essential g++ bash make libssl-dev patch libncurses5 libncurses5-dev zlib1g-dev gawk flex gettext wget unzip xz-utils python3-distutils-extra python3 python3-distutils-extra python3-setuptools swig rsync curl libsnmp-dev liblzma-dev libpam0g-dev cpio rsync gcc-multilib 
          sudo apt-get autoremove --purge
          sudo apt-get clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p $home_dir
          sudo chown $USER:$GROUPS $home_dir

      - name: "拉取openwrt源码"
        working-directory: /mnt/app
        run: |
          df -hT $PWD
          git clone $repo_url openwrt
          cd openwrt
          git checkout $repo_tag 
          ln -sf $home_dir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: "复制feeds配置文件"
        run: |
          cp build_config/feeds.conf.default $home_dir/openwrt/feeds.conf.default
          cat $home_dir/openwrt/feeds.conf.default
      - name: "更新feeds"
        working-directory: /mnt/app/openwrt
        run: ./scripts/feeds update -a

      - name: "安装feeds golang"
        working-directory: /mnt/app/openwrt
        run: |
          rm -rf feeds/packages/lang/golang
          git clone https://github.com/sbwml/packages_lang_golang -b 22.x feeds/packages/lang/golang

      - name: "安装feeds"
        working-directory: /mnt/app/openwrt
        run: ./scripts/feeds install -a

      - name: "复制编译配置文件"
        run: |
          cp build_config/.config $home_dir/openwrt/.config
          mkdir -p $home_dir/openwrt/files/etc/uci-defaults
          cp build_config/99-custom $home_dir/openwrt/files/etc/uci-defaults/99-custom
          ls -alh $home_dir/openwrt/

      - name: "编译器 缓存 "
        uses: actions/cache@v3
        env:
          cache-name: openwrt-ccache
        with:
          path: |
            ~/.ccache/
            /mnt/app/openwrt/staging_dir 
            /mnt/app/openwrt/build_dir
            /mnt/app/openwrt/dl
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: "下载编译所需软件源码"
        working-directory: /mnt/app/openwrt
        run: make defconfig && make download -j$(nproc)|| make download -j1 V=s

      - name: "开始编译"
        working-directory: /mnt/app/openwrt
        run: make -j$(nproc) || make -j1 V=s

      - name: "上传编译产物"
        uses: actions/upload-artifact@v4
        with:
          name: openwrt_bin
          path: /mnt/app/openwrt/bin
